### ISSUE TITLE
Migrating runtime from GNOME 3.36 to GNOME 40

### ISSUE THREAD

**Issue by ghost** [flathub/in.bharatkalluri.splash#1]
Upon updating their Flatpak apps, users are informed with this message:
`Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.`

While updating the runtime version from `3.36` to `40` is sufficient, there are regressions. Specifically, the app cannot set the background image anymore. What more should be done to get this functionality working in the GNOME 40 runtime?

**Comment by bbhtt** [comment]
I've opened https://gitlab.gnome.org/Bharatkalluri/splash/-/issues/3 and a few other issues.
