### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/in.bharatkalluri.splash#4]
https://gitlab.gnome.org/Bharatkalluri/splash/-/blob/d1739db63642a3b1d4097d9e8a1c2c98630f91e8/data/in.bharatkalluri.splash.desktop.in#L6

This is due to the desktop file having a low quality category that is filtered by appstream
Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

**Comment by hfiguiere** [comment]
With #5
